---
title: "Inferring patient-specific cancer dependencies through integrating ex-vivo drug response assays and drug-protein profiling"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

<font size="4">This is the workflow that generates the data analysis results and figures presented in the manuscript "Inferring patient-specific cancer dependencies through integrating ex-vivo drug response assays and drug-protein profiling" by Batzilla and Lu et al. Users can also use the associated source code to reproduce all results and figures in the manuscript.</font>  

# Table of contents

## Section 1: Data pre-processing

### [1.1 Drug-target profiling (Kinobeads) data. ](./process_kinobeads.html)  

### [1.2 Genomics of Drug Sensitivity in Cancer (GDSC) dataset](./process_GDSC.html)

### [1.3 BeatAML drug screen dataset](./process_beatAML.html)

### [1.4 Ex-vivo drug screen on primary CLL samples](./process_EMBL2016.html) 


## Section 2: Data analysis

### [2.1 Protein dependency inference based on the GDSC cell line screen data](./analysis_GDSC.html)

### [2.2 Protein dependency inference based on the BeatAML screen data](./analysis_beatAML.html) 

### [2.3 Protein dependency inference and association analysis based on in-house screen data on primary CLL samples](./analysis_EMBL2016.html)

### [2.4 Investigating CHEK1 related transcriptomic signatures in primary CLL samples](analysis_RNAseq.html)
